ymin_cold_temp1 = 480
ymax_cold_temp1 = 520
ymin_cold_temp2 = 2040
ymax_cold_temp2 = 2100


ymin_hot_ang1 = 265
ymax_hot_ang1 = 266
ymin_hot_ang2 = 273
ymax_hot_ang2 = 275


ymin_earth_ang1 = 40
ymax_earth_ang1 = 41
ymin_earth_ang2 = 265
ymax_earth_ang2 = 266


ymin_ira_colder2_volt = 1810
ymax_ira_colder2_volt = 1880

ymin_prt = 292
ymax_prt = 294

ymin_ira_mirdir_sign = 160
ymax_ira_mirdir_sign = 220

